apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: daskous/mykuberepo:users-api
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              #value: "10.110.43.220"
              value: "auth-service.default"
          # ports:
          #   - containerPort: 8080
          # volumeMounts:
          #   - name: tasks-volume
          #     mountPath: /tasks